name: Publish release

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

    - run: dotnet build --configuration Release

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Publish the package to Nuget Gallery
      run: dotnet nuget push Sethealth.net/bin/Release/*.nupkg

